Try to get it to work with linking packages but build fails
[Vue warn]: Component VuepressApp  is missing template or render function.
Error: usePageHead() is called without provider.